USE [master]
GO

/****** Object:  Database [Hospitals]    Script Date: 9/11/2023 12:31:52 PM ******/
CREATE DATABASE [Hospitals]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Hospitals', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\Hospitals.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Hospitals_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\Hospitals_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Hospitals].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Hospitals] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Hospitals] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Hospitals] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Hospitals] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Hospitals] SET ARITHABORT OFF 
GO

ALTER DATABASE [Hospitals] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Hospitals] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Hospitals] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Hospitals] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Hospitals] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Hospitals] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Hospitals] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Hospitals] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Hospitals] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Hospitals] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Hospitals] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Hospitals] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Hospitals] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Hospitals] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Hospitals] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Hospitals] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Hospitals] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Hospitals] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Hospitals] SET  MULTI_USER 
GO

ALTER DATABASE [Hospitals] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Hospitals] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Hospitals] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Hospitals] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Hospitals] SET  READ_WRITE 
GO

